config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :agencies do
    collection do
      get "compare", to: "agencies#compare"
      get 'search', to: "agencies#search"
      post 'search', to: "agencies#search"

    end
    resources :reviews, only: [:new, :create]
    resources :references, only: [:new, :create]
    resources :quotes, only: [:new, :create]
  end

#  require "sidekiq/web"
#  authenticate :user, lambda { |u| u.admin } do
#    mount Sidekiq::Web => '/sidekiq'
#  end

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/agency.rb
class Agency < ApplicationRecord

  mount_uploader :photo, PhotoUploader

  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :references, dependent: :destroy
  has_many :quotes


  after_create :enrich_github
  after_create :enrich_linkedin



  def review_mean
   if self.reviews.length == 0
      0
    else
      sum = self.reviews.reduce(0){|memo, review| memo+=review.star}
      sum.fdiv(self.reviews.count)
   end
  end




  def short_description
    "#{self.description[0..140]} ..." unless self.description.nil?
  end


  private

  def enrich_github
    if self.github_account
      GithubEnrichmentJob.perform_now(self.id)
    end
  end

  def enrich_linkedin
    if self.linkedin_account
      LinkedinEnrichmentJob.perform_now(self.id)
    end
  end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :user
  belongs_to :agency
end

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :agency
  mount_uploader :photo, PhotoUploader

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :agency
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :agencies, dependent: :destroy
  has_many :reviews
  has_many :quotes
  mount_uploader :photo, PhotoUploader


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def full_name
    first_name = self.first_name.nil? ? '' :self.first_name.capitalize
    last_name = self.last_name.nil? ? '' :self.last_name.capitalize
    return "#{first_name.capitalize} #{last_name.capitalize} "
  end

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:compare, :index, :show]

  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  def index
    @agencies = Agency.all

  end

  def search
    @agencies = Agency.where("description = ?", params[:what])

  end

  # GET /agencies/1
  def show
    @agency = Agency.find(params[:id])
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  def create
    @agency = Agency.new(agency_params)


    if @agency.save
      redirect_to @agency, notice: 'Agency was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /agencies/1
  def update
        @agency = Agency.find(params[:id])

    if @agency.update(agency_params)
      redirect_to @agency, notice: 'Agency was successfully updated.'
    else
      render :edit
    end
  end

  def compare
    ids = params[:ids].split(',')
    @agencies = []
    ids.each do |id|
      @agencies << Agency.find(id)
    end
  end

  # DELETE /agencies/1
  def destroy
    @agency.destroy
    redirect_to agencies_url, notice: 'Agency was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def agency_params
      params.require(:agency).permit(:name, :description, :address, :user_id, :where, :photo, :photo_cache)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:home]
  def home
    @agencies = Agency.all[0..3]
    @reviews = Review.all[0..3]
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_agency, only: [:new, :create]

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # POST /quotes
  def create
    @quote = @agency.quotes.new(quote_params)
    if @quote.save!
      redirect_to @quote.agency, notice: 'Quote was successfully recorded.'
    else
      render @agency
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_agency
    @agency = Agency.find(params[:agency_id])
  end

  # Only allow a trusted parameter "white list" through.
  def quote_params
    params.require(:quote).permit(:description, :agency_id, :user_id)
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_agency, only: [:new, :create]

  def index
    @references = Reference.all
  end


   def new
    @reference = Reference.new
  end

  def show
  end

  # POST /agencies
  def create
    @reference = @agency.references.new(reference_params)
    if @reference.save!
      redirect_to @reference.agency, notice: 'Reference was successfully recorded.'
    else
      render @agency
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_agency
    @agency = Agency.find(params[:agency_id])
  end

  # GET /agencies

def reference_params
  params.require(:reference).permit(:name, :description, :photo, :photo_cache, :agency_id)
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_agency, only: [:new, :create]

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # POST /reviews
  def create
    @review = @agency.reviews.new(review_params)
    if @review.save!
      redirect_to @review.agency, notice: 'Review was successfully recorded.'
    else
      render @agency
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_agency
    @agency = Agency.find(params[:agency_id])
  end

  # Only allow a trusted parameter "white list" through.
  def review_params
    params.require(:review).permit(:description, :agency_id, :user_id, :star)
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/views/agencies/_agency.html.erb
<%= link_to agency_path(agency) do%>

<div class="agency-card">
  <%= cl_image_tag agency.photo, width: 300, height:  100, crop: :pad %>
  <% end %>
  <h2><%= agency.name %></h2>
  <p> <%= agency.short_description %></p>
  <div class="stars">
    <% agency.review_mean.to_i.times do %>
      <i class="fa fa-star"></i>
    <% end %>
  </div>
</div>

app/views/agencies/_cards.html.erb
<div class="container">
  <h2 class="text-center uppercase">Nos derniers avis </h2>
  <div class="row">
    <% @agency.reviews.each do |review|%>
    <div class="col-xs-12 col-md-4">
      <div class="card-review">
        <%= image_tag review.user.photo, class:"avatar card-avatar"  %>
        <div class="card-star stars">
          <% review.star.to_i.times do %>
            <i class="fa fa-star"></i>
          <% end %>
        </div>
        <div class="card-title">
          <h4><%= review.user.full_name %></h4>
        </div>

        <div class="card-quote">
        <div class="quote-wrapper">
          <p class="quote-start quote-tick">"</p>
           <p class="quote-content"> <%= review.description %></p>
           <p class="quote-end quote-tick">"</p>
        </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/agencies/_form.html.erb
<%= simple_form_for(@agency) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id, as: :hidden, :input_html => { :value => current_user.id.to_s } %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/agencies/_review.html.erb
<div class="card-review">
  <%= image_tag review.user.photo, class:"avatar card-avatar"  %>
  <div class="card-star stars">
    <% review.star.to_i.times do %>
      <i class="fa fa-star"></i>
    <% end %>
  </div>
  <div class="card-title">
    <h4><%= review.user.full_name %></h4>
  </div>

  <div class="card-quote">
  <div class="quote-wrapper">
    <p class="quote-start quote-tick">"</p>
     <p class="quote-content"> <%= review.description %></p>
     <p class="quote-end quote-tick">"</p>
  </div>
  </div>
</div>

app/views/agencies/compare.html.erb
<h1>comparaison</h1>

app/views/agencies/edit.html.erb
<h1>Editing Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="agency-list">
  <div class="padded">
  <div class="container">
    <div class="row">
    <h1 class="text-center">Les agences suscesptibles de vous intéresser:</h1>
    <div class="separator">
    <div class="separator-line">
    </div>
    </div>
      <% @agencies.each do |agency| %>
        <div class="col-xs-12 col-md-4">
          <%= render "agencies/agency", :agency => agency %>
        </div>
      <% end %>
    </div>
  </div>

  </div>

  <br>

  <%= link_to 'New Agency', new_agency_path %>

</div>

app/views/agencies/new.html.erb
<h1>New Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/search.html.erb
<p id="notice"><%= notice %></p>





<div class="padded">
<h1 class="text-center">Vos agences :</h1>
<div class="agency-card">
  <% @agencies.each do |agency| %>
  <%= cl_image_tag agency.photo, width: 300, height:  100, crop: :pad %>
  <h2><%= agency.name %></h2>
  <p> <%= agency.short_description %></p>
  <div class="stars">
    <% agency.review_mean.to_i.times do %>
      <i class="fa fa-star"></i>
    <% end %>
    <% end %>
  </div>
</div>

</div>




<br>

<%= link_to 'New Agency', new_agency_path %>

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center justify"><u> Informations sur votre agence : </u></h1>

<div class="padded" background-color:"#E8E8E8">
  <div class="container">
    <div class="row">

      <div class="col-xs-12 col-md-8" id="description">
        <%= cl_image_tag @agency.photo, crop: "pad", class: "logo-md" %>
      <p>
      <strong> <u> Name: </u></strong>
      <%= @agency.name %>
      </p>

      <p>
      <strong> <u> Description:</u> </strong>
      <%= @agency.description %>
      </p>

      <p>
      <strong> <u> Address: </u> </strong>
      <%= @agency.address %>
      </p>


      <p>
      <strong> <u> Github info: </u> </strong>
      <%= @agency.repos_public %>
      <%= @agency.total_stars %>
      <%= @agency.total_members %>
      </p>

      <p>
      <strong><u> References: </u></strong>
      </p>
      <% @agency.references.each do |r| %>
      <p> <%= r.name %> </p>
      <p> <%= r.description %> </p>
      <%= cl_image_tag r.photo, crop: :fill %>
      <% end %>

      <p>
      <strong> <u> Reviews: </u> </strong>
      </p>

      <p> <%= @agency.review_mean.to_i.times do %>
            <i class="fa fa-star"></i>
      <% end %>
      </p>


      <div class="text-center" id="bottom-link">
      <%= link_to 'Add a Review', new_agency_review_path(@agency) %> |
      <%= link_to 'Add a Reference', new_agency_reference_path(@agency) %> |
      <%= link_to 'Edit', edit_agency_path(@agency) %> |
      <%= link_to 'Back', agencies_path %>
      </div>

      </div>
      <div class="col-xs-12 col-md-4" id="description">
        <div class ="padded-product text-center">
          <%= link_to 'Ask for a quote', new_agency_quote_path(@agency), :class => "btn btn-danger" %>
        </div>
        <br>
        <div class="col-xs-12 col-md-12" id="description">
      <%= cl_image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@agency.address}&size=600x300&maptype=roadmap", class: "full" %>
      </div>
      </div>
 </div>
</div>


<!-- ajouter l'img de la home = ligne/fleche orange -->
 <div id="color">
  <h3> Reviews </h3>
  <%= image_tag('color-bar.png', class:"full" ) %>
  </div>


<!-- La carte -->

<!-- <div class="padded">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
      <%= cl_image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@agency.address}&size=600x300&maptype=roadmap", class: "full" %>
      </div>
    </div>
  </div>
</div> -->

<!-- Toutes les reviews -->

<div class="container">
  <div class="row">
      <% @agency.reviews.each do |review| %>
        <div class="col-xs-offset-2 col-xs-8">
          <%= render 'agencies/review', :review => review %>
        </div>
      <% end %>
  </div>
</div>

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title>Devsolut</title>
      <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body class="<%= "#{controller_name} #{action_name}" %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

      <%= csrf_meta_tags %>
      <%= action_cable_meta_tag %>

      <title><%= meta_title %></title>
      <meta name="description" content="<%= meta_description %>">

      <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url(meta_image) %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META[:twitter_account] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META[:twitter_account] %>">
    <meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    <meta itemprop="image" content="<%= image_url(meta_image) %>">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body class="<%= "#{controller_name}-#{action_name}" %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= yield :after_js %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/home.html.erb
    <div class="banner" style="background-image: linear-gradient(-225deg, rgba(255, 255, 255, 0.4) 100%, rgba(255, 255, 255, 0.4) 100%), url('<%= image_path "fondbanner3.png" %>')">
      <div class="banner-content">
          <h1>Trouvez les meilleures agences webs</h1>

<!-- Formulaire à refactoriser avec un form_tag -->
        <%= form_tag search_agencies_path do %>
        <%= select_tag "agency[where]", options_for_select([ "France", "Ile de France" ], "France"),  class: "form-control btn btn-danger dropdown-toggle" %>
        <%= select_tag "agency[what]", options_for_select([ "Developpement web", "Developpement mobile" ], "Developpement web"), class: "form-control btn btn-danger dropdown-toggle" %>
        <%= button_tag "Trouver", class: "btn btn-default btn-lg btn-block" %>
        <% end %>
<!-- end -->

      </div>
    </div>


<!-- A propos/services -->

<div class="padded">
  <div class="container">
    <h3 class="text-center">Nos services</h3>
    <div class="separator">
      <div class="separator-line">
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-4">
      <div class="feature">
        <%= image_tag "bookmark.png"%>
        <h3>Catalogue</h3>
        <p>Accédez à un catalogue complet de toutes les agences de developpement web et mobile partout en France.</p>
      </div>
      </div>

      <div class="col-xs-12 col-sm-4">
      <div class="feature">

        <%= image_tag "diploma.png"%>
        <h3>Classement</h3>
        <p>Pour faire le bon choix visualisez les notes des agences sur 3 critères : compétences, influence, et avis clients. </p>
      </div>
      </div>


        <div class="col-xs-12 col-sm-4">
          <div class="feature">

          <%= image_tag "1456955809_clock.png"%>
          <h3>Devis et confidentialité</h3>
          <p>Obtenez en 48h un devis gratuit et un contrat de confidentialité pour des échanges en toute sécurité.</p>
          </div>
        </div>
    </div>
  </div>
</div>


<!-- Top des agences -->

<div class="padded">
  <div class="container">
    <h2 class="text-center uppercase">Nos agences </h2>
    <div class="row">
      <% @agencies.each do |agency|%>
      <div class="col-xs-12 col-md-4">
        <%= render "agencies/agency", agency: agency %>
      </div>
      <% end %>
    </div>
  </div>
</div>


<!-- Testimonials -->

<div class="padded">
<div class="container">
  <h2 class="text-center uppercase">Nos derniers avis </h2>
  <div class="row">
    <% @reviews.each do |review|%>
    <div class="col-xs-12 col-md-4">
      <div class="card-review">
        <%= image_tag review.user.photo, class:"avatar card-avatar"  %>
        <div class="card-star stars">
          <% review.star.to_i.times do %>
            <i class="fa fa-star"></i>
          <% end %>
        </div>
        <div class="card-title">
          <h4><%= review.user.full_name %></h4>
        </div>
        <div class="card-quote">
        <div class="quote-wrapper">
          <p class="quote-start quote-tick">"</p>
          <p class="quote-content"> <%= review.description %></p>
          <p class="quote-end quote-tick">"</p>
        </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/quotes/_form.html.erb
<%= simple_form_for [@agency, @quote] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id, as: :hidden, :input_html => { :value => current_user.id.to_s } %>
    <%= f.input :titre %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', agencies_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.user.first_name %></td>
        <td><%= quote.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', agencies_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', agencies_path(@agency), class: 'btn btn-default btn-xs' %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @quote.user.first_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @quote.description %>
</p>

<%= link_to 'Back', agency_path %>

app/views/references/_form.html.erb
<%= simple_form_for [@agency, @reference] do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
    </div>
  <div class="form-actions">
  <%= f.button :submit %>
    </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editing Reference</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', reference_agency_path(agency) %>

app/views/references/new.html.erb
<h1>New Reference</h1>

<%= render 'form', references: @reference %>

<%= link_to 'Back', agency_path(@agency), class: 'btn btn-default btn-xs' %>

app/views/references/show.html.erb
<%= cl_image_tag @reference.photo, height: 300, width: 400, crop: :fill %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@agency, @review] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id, as: :hidden, :input_html => { :value => current_user.id.to_s } %>
    <%= f.input :description %>
    <%= f.input :star %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.user.first_name %></td>
        <td><%= review.description %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agency', new_agency_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', agency_path(@agency), class: 'btn btn-default btn-xs' %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @review.user.first_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">

  <div class="container">
    <div class="row">

      <div class="col-xs-6 pull-left">
        <ul class="list-inline">
          <li><a href=""><i class="fa fa-linkedin"></i></a></li>
          <li><a href=""><i class="fa fa-facebook"></i></a></li>
          <li><a href=""><i class="fa fa-twitter"></i></a></li>

        </ul>
      </div>

      <div class="col-xs-6 text-right">
        <p>@DEVSOLUT</p>
      </div>


    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-fixed-top">

    <!--Menu côté droit-->

    <div class="navbar-right">

      <a href="users/sign_in" class="navbar-item navbar-link btn btn-small" id="refe">Se référencer</a>
      <a href="#feature-container1" class="navbar-item navbar-link">À propos</a>
      <a href="users/sign-up" class="navbar-item navbar-link">Inscription</a>
      <a href="/users/sign_up" class="navbar-item navbar-link">Connexion</a>

    </div>


     <div class="navbar-left">

      <a href="#" class="navbar-item navbar-link" style="font-weight: bolder; font-size: 18px;">Devsolut</a>
      <%= image_tag "logo-dev.png", id: "navbar-logo" %>
     </div>
</nav>